---
- name: Certificates Linux Delivery
  hosts: "{{ HOSTS_GROUP | default('LINTER_MOCK_GROUP') }}"
  become: true

  tasks:
    - name: Certificates Delivery for Debain Based
      when: ansible_os_family == "Debian"
      block:
        - name: CA certificates package check for Debian Based
          ansible.builtin.apt:
            name: ca-certificates
            state: present

        - name: Copy .crt files for Debian Based
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "/usr/local/share/ca-certificates/"
            owner: root
            group: root
            mode: '0644'
          loop: "{{ lookup('fileglob', '/ansible/files/certs/*.crt', wantlist=True) }}"
          notify: ca-cert-upd-Debian

    - name: Certificates Delivery for RadHat Based
      when: ansible_os_family == "RedHat"
      block:
        - name: CA certificates package check for RedHat based
          ansible.builtin.dnf:
            name: ca-certificates
            state: present

        - name: Copy .crt files for RedHat Based
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "/etc/pki/ca-trust/source/anchors/"
            owner: root
            group: root
            mode: '0644'
          loop: "{{ lookup('fileglob', '/ansible/files/certs/*.crt', wantlist=True) }}"
          notify: ca-cert-upd-RedHat

  handlers:
    - name: Update ca-certificates for Debian Based
      ansible.builtin.command: update-ca-certificates
      listen: ca-cert-upd-Debian
      when: ansible_os_family == "Debian"
      changed_when: true

    - name: Update ca-certificates for RadHat Based
      ansible.builtin.command: update-ca-trust extract
      listen: ca-cert-upd-RadHat
      when: ansible_os_family == "RedHat"
      changed_when: true