---
# 
# Uploading handlers
# 
- name: Uploading handler for CA-certificates task
  ansible.builtin.include_tasks: "CA-certificates/{{ ansible_os_family }}.yml"
  listen: "Update ca-certificates"
- name: Uploding handler for SSH-reload
  ansible.builtin.include_tasks: "SSH/reload-sshd.yml"
  listen: "reload sshd"

# 
# Uploading vars
# 
- name: Upload package's names based on OS Family
  ansible.builtin.include_vars: "Packages/{{ ansible_os_family }}.yml"
- name: Upload aministrator's inf. for user creation
  ansible.builtin.include_vars: "Users/admins.yml"

# 
# Including tasks
# 
- ansible.builtin.include_tasks: "Packages/packages-installation.yml"
- ansible.builtin.include_tasks: "CA-certificates/{{ ansible_os_family }}.yml"
- ansible.builtin.include_tasks: "SSH/ssh-hardening.yml"