---
- name: CA certificates package check
  ansible.builtin.apt:
    name: ca-certificates
    state: present

- name: Copying .crt files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/share/ca-certificates/"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ lookup('fileglob', '/ansible/files/certs/*.crt', wantlist=True) }}"
  notify: Update ca-certificates