---
- name: SSH Configuration. Turning Off Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "PermitRootLogin yes"
    line: "PermitRootLogin no"
  notify: reload sshd