---
- name: SSH Configuration. Turning Off Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?\\s*PermitRootLogin\\s+.*$"
    line: "PermitRootLogin no"
    validate: 'sshd -t -f %s'
  notify: "reload sshd"