---
- name: Изменить pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
  notify: psql-daemon-reboot

- name: Запуск handlers сразу
  ansible.builtin.meta: flush_handlers
