---
- name: Изменить pg_hba.conf
  ansible.builtin.template:
    src: templates/pg_hba.conf.j2
    dest: /etc/postgresql/16/main/
  notify: psql-daemon-reboot

- name: Запуск handlers сразу
  ansible.builtin.meta: flush_handlers
